window.PeriodSathiData = {
  provinces: [
    {
      name: "Sudurpashchim",
      nameNe: "सुदूरपश्चिम",
      access: 18,
      note: "Chhaupadi still practiced in remote districts",
      color: "#DC143C",
      path: "M60 60 L100 40 L150 50 L170 80 L150 110 L100 125 L70 100 L60 75 Z",
    },
    {
      name: "Karnali",
      nameNe: "कर्णाली",
      access: 28,
      note: "Most remote, lowest service continuity",
      color: "#F97316",
      path: "M100 40 L140 25 L210 35 L240 60 L220 90 L140 110 L100 95 L100 60 Z",
    },
    {
      name: "Lumbini",
      nameNe: "लुम्बिनी",
      access: 45,
      note: "Improving urban access, rural gaps remain",
      color: "#F59E0B",
      path: "M140 50 L180 35 L240 50 L300 90 L270 140 L210 165 L170 150 L140 115 Z",
    },
    {
      name: "Gandaki",
      nameNe: "गण्डकी",
      access: 52,
      note: "Moderate health-post reach",
      color: "#84CC16",
      path: "M210 35 L260 20 L340 30 L380 70 L360 120 L300 135 L250 115 L210 85 Z",
    },
    {
      name: "Bagmati",
      nameNe: "बागमती",
      access: 78,
      note: "Kathmandu-centered specialist access",
      color: "#10B981",
      path: "M260 20 L320 5 L410 25 L460 70 L430 115 L380 130 L320 120 L280 85 Z",
    },
    {
      name: "Madhesh",
      nameNe: "मधेश",
      access: 42,
      note: "Dense population, uneven adolescent health services",
      color: "#F59E0B",
      path: "M210 85 L260 70 L340 85 L420 120 L480 190 L450 240 L360 260 L300 220 L250 190 Z",
    },
    {
      name: "Koshi",
      nameNe: "कोशी",
      access: 55,
      note: "Better eastern corridor, mountain districts underserved",
      color: "#22C55E",
      path: "M300 5 L360 5 L450 20 L540 60 L600 140 L570 200 L500 230 L440 190 L390 130 L350 90 Z",
    },
  ],

  stats: [
    { icon: "🌸", value: 88, suffix: "%", label: "Women using unsafe period materials", labelNe: "असुरक्षित सामग्री प्रयोग गर्ने महिला" },
    { icon: "📚", value: 71, suffix: "%", label: "Girls missing school during periods", labelNe: "महिनावारीमा विद्यालय छुटाउने किशोरी" },
    { icon: "🏥", value: 28, suffix: "%", label: "Karnali women accessing health services", labelNe: "कर्णालीमा सेवा पाउने महिला" },
    { icon: "🤝", value: 10, suffix: "+", label: "Partner NGOs across Nepal", labelNe: "नेपालभर साझेदार संस्था" },
  ],

  features: [
    { icon: "🤖", title: "AI Chatbot", text: "Ask anything, safely and anonymously", route: "chatbot" },
    { icon: "📅", title: "Period Tracker", text: "Track your cycle, understand your body", route: "tracker" },
    { icon: "📖", title: "Education Hub", text: "Facts not myths, science not shame", route: "education" },
    { icon: "🏥", title: "Find Help", text: "Hospitals and NGOs near you", route: "hospital-finder" },
    { icon: "💬", title: "Community", text: "You are not alone", route: "community" },
    { icon: "🌿", title: "Day Guide", text: "What your body needs, day by day", route: "tracker" },
  ],

  testimonials: [
    {
      quote: "म पहिले सोच्थें मेरो पीडा सामान्य हो। यो platform ले मलाई सत्य बुझाइदियो।",
      author: "Sita",
      age: 19,
      place: "Sindhupalchok",
      initials: "S",
    },
    {
      quote: "छाउपडीको डरले मैले कहिल्यै कुरा गरिन। अब म आफ्नो स्वास्थ्यको लागि बोल्छु।",
      author: "Maya",
      age: 24,
      place: "Humla",
      initials: "M",
    },
    {
      quote: "AI chatbot ले मेरो सबै प्रश्नहरूको जवाफ दियो जुन मैले आफ्नी आमालाई सोध्न सकिन।",
      author: "Priya",
      age: 17,
      place: "Morang",
      initials: "P",
    },
  ],

  myths: [
    {
      id: 1,
      category: "Health",
      myth: "Touching a plant during periods will kill it",
      mythNe: "महिनावारीमा बिरुवा छोए मरिन्छ",
      common: "Karnali, Sudurpashchim",
      fact: "There is no scientific basis for this belief. Plants are unaffected by menstruating women.",
      source: "UNICEF Nepal / WHO",
    },
    {
      id: 2,
      category: "Religious",
      myth: "You cannot enter the temple or worship gods",
      mythNe: "महिनावारीमा मन्दिर जानु हुँदैन",
      common: "Bagmati, Lumbini, Madhesh",
      fact: "Menstruation is a biological process. It does not make anyone spiritually impure.",
      source: "Kathmandu Medical College",
    },
    {
      id: 3,
      category: "Hygiene",
      myth: "You should not wash your hair during periods",
      mythNe: "महिनावारीमा कपाल धुनु हुँदैन",
      common: "Koshi, Gandaki",
      fact: "Washing hair is safe and hygienic during menstruation. Cleanliness lowers infection risk.",
      source: "WHO",
    },
    {
      id: 4,
      category: "Food",
      myth: "You shouldn't eat sour foods like tamarind or achar",
      mythNe: "अमिलो खाँदा महिनावारी बिग्रिन्छ",
      common: "Madhesh, Lumbini",
      fact: "Sour foods do not harm menstrual health. Vitamin C in citrus can help iron absorption.",
      source: "Nutrition Society Nepal",
    },
    {
      id: 5,
      category: "Health",
      myth: "Irregular periods mean you are cursed",
      mythNe: "अनियमित महिनावारी श्राप हो",
      common: "Rural Nepal",
      fact: "Irregular cycles can be caused by PCOS, thyroid issues, stress, nutrition deficits, or weight changes.",
      source: "WHO / Nepal Health Research Council",
    },
    {
      id: 6,
      category: "Exercise",
      myth: "You shouldn't exercise during your period",
      mythNe: "महिनावारीमा व्यायाम गर्नु हुँदैन",
      common: "National",
      fact: "Light exercise like yoga and walking can reduce cramps and improve mood.",
      source: "Kathmandu Medical College",
    },
    {
      id: 7,
      category: "Health",
      myth: "Periods should be exactly 28 days apart",
      mythNe: "महिनावारी ठीक २८ दिनमै आउनुपर्छ",
      common: "National",
      fact: "Normal cycles range from 21 to 35 days. Your body can have natural variation.",
      source: "WHO",
    },
    {
      id: 8,
      category: "Health",
      myth: "Period blood is dirty or toxic",
      mythNe: "महिनावारीको रगत फोहोर वा विषालु हुन्छ",
      common: "National",
      fact: "Menstrual fluid contains blood, uterine lining tissue, and vaginal secretions. It is not toxic.",
      source: "UNICEF Nepal",
    },
    {
      id: 9,
      category: "Religious",
      myth: "Talking about periods brings bad luck",
      mythNe: "महिनावारीबारे बोल्दा अशुभ हुन्छ",
      common: "Sudurpashchim, Karnali",
      fact: "Open discussion is essential for health. Shame causes dangerous delays in care.",
      source: "WOREC Nepal",
    },
    {
      id: 10,
      category: "Hygiene",
      myth: "Pads are only for city women; cloth is fine",
      mythNe: "प्याड सहरका महिलाका लागि मात्र हो",
      common: "Rural Nepal",
      fact: "Clean cloth can be used safely only if washed with soap, sun-dried, and stored dry. Unclean cloth can cause infections.",
      source: "UNICEF Nepal",
    },
  ],

  dayGuide: [
    {
      range: "Day 1",
      day: 1,
      phase: "Menstrual Phase",
      flow: "Heavy flow, high discomfort",
      happening: "Uterine lining sheds. Prostaglandins cause cramps. Estrogen and progesterone are at their lowest.",
      symptoms: ["Heavy bleeding", "Cramps", "Headache", "Fatigue", "Lower back pain"],
      mood: "Low energy, irritable, sad",
      eat: ["Spinach / पालुंगो", "Dal soup", "Beetroot", "Dark chocolate", "Banana"],
      avoid: ["Caffeine", "Cold drinks", "Processed food"],
      remedy: "Ginger tea with honey, heating pad on lower abdomen, and light stretching.",
      exercise: "Rest or gentle walking.",
      tip: "अदुवा चिया र मह — पहिलो दिनको सबैभन्दा राम्रो साथी",
    },
    {
      range: "Day 2",
      day: 2,
      phase: "Menstrual Phase",
      flow: "Still heavy, slightly better",
      happening: "Bleeding continues. Your body is in repair mode.",
      symptoms: ["Moderate-heavy bleeding", "Cramps", "Bloating"],
      mood: "Emotionally sensitive, tearful",
      eat: ["Sesame / तिल", "Fenugreek / मेथी", "Warm soup", "Jaggery / खाँद"],
      avoid: ["Salty snacks", "Cold water"],
      remedy: "Warm water bottle, chamomile tea, or jwano with warm water.",
      exercise: "Child's Pose and Cat-Cow yoga.",
      tip: "ज्वानो र न्यानो पानी — पेट दुखाइको घरेलु उपाय",
    },
    {
      range: "Day 3",
      day: 3,
      phase: "Menstrual Phase",
      flow: "Flow lightens",
      happening: "Estrogen starts rising. Your body begins recovery.",
      symptoms: ["Lighter flow", "Reduced cramps", "Tiredness"],
      mood: "Slightly better, more stable",
      eat: ["Papaya / मेवा", "Eggs", "Walnuts", "Almonds", "Yogurt / दही"],
      avoid: ["Alcohol", "Heavy red meat"],
      remedy: "Cinnamon tea or turmeric milk.",
      exercise: "Light yoga, stretching, short walks.",
      tip: "हल्दी दूध — नेपाली महिलाको प्राकृतिक औषधि",
    },
    {
      range: "Day 4",
      day: 4,
      phase: "Menstrual Phase",
      flow: "Very light bleeding or spotting",
      happening: "Estrogen rises steadily. The uterus is nearly recovered.",
      symptoms: ["Spotting", "Minimal cramps", "Energy returning"],
      mood: "More optimistic",
      eat: ["Green vegetables", "Lemon water", "Pomegranate / अनार", "Fish"],
      avoid: ["No strict restriction"],
      remedy: "Fenugreek seed tea if bloated.",
      exercise: "Moderate walk, light swimming, beginner Pilates.",
      tip: "आज तपाईं राम्रो महसुस गर्नुहुन्छ — बिस्तारै सक्रिय हुनुहोस्",
    },
    {
      range: "Day 5",
      day: 5,
      phase: "Menstrual Phase",
      flow: "End of period",
      happening: "Bleeding usually stops. Estrogen peak begins.",
      symptoms: ["Minimal bleeding", "Energy good"],
      mood: "Positive, motivated, creative",
      eat: ["Spinach + lemon", "Eggs", "Daal", "Whole grains"],
      avoid: ["Nothing specific"],
      remedy: "Stay hydrated and rebuild iron.",
      exercise: "Resume normal exercise, brisk walking, jogging, cycling.",
      tip: "अब तपाईं शक्तिशाली हुनुहुन्छ!",
    },
    {
      range: "Days 6-14",
      day: 9,
      phase: "Follicular Phase",
      flow: "No bleeding",
      happening: "Estrogen peaks. Follicles develop. Energy, confidence, and clarity rise.",
      symptoms: ["More energy", "Clearer focus", "Confidence"],
      mood: "Social, creative, confident",
      eat: ["Lean proteins", "Gundruk", "Yogurt", "Seeds", "Green tea"],
      avoid: ["Skipping meals"],
      remedy: "Use this energy for goals and connection.",
      exercise: "Physical challenges feel easier.",
      tip: "ठूला कामका लागि यो समय राम्रो हुन्छ।",
    },
    {
      range: "Days 15-28",
      day: 22,
      phase: "Luteal Phase",
      flow: "No bleeding, PMS may begin later",
      happening: "Progesterone rises then falls. PMS can set in after Day 21.",
      symptoms: ["Bloating", "Cravings", "Irritability", "Breast tenderness"],
      mood: "Gentle self-care matters",
      eat: ["Dark chocolate", "Avocado", "Banana", "Chickpeas", "Sesame"],
      avoid: ["Too much caffeine", "Overscheduling"],
      remedy: "Journaling, rest, and fewer social obligations.",
      exercise: "Yoga, walking, and mobility.",
      tip: "आफूलाई कठोर होइन, कोमल हुनुहोस्।",
    },
  ],

  chatbotResponses: [
    {
      keys: ["cramp", "pain", "dukhai", "dukhyo", "dukh", "पेट", "दुख"],
      topic: "Period cramps",
      response:
        "Period cramps are caused by prostaglandins that make your uterus contract.\n\n🌿 Natural remedies:\n• Ginger tea with honey, warm, 2-3 times/day\n• Carom seeds (jwano) in warm water\n• Heating pad on lower abdomen for 15-20 minutes\n• Light yoga: Child's Pose, Supine Twist\n\n🍎 Helpful foods: dark chocolate, banana, spinach soup, turmeric milk\n❌ Avoid: cold drinks, caffeine, salty snacks\n\nIf pain is severe, sudden, one-sided, or stops daily life, please consult a doctor.",
    },
    {
      keys: ["irregular", "late", "niyamit", "cycle", "chakra", "delay", "छैन", "ढिला"],
      topic: "Irregular periods",
      response:
        "Irregular periods are common and usually not dangerous.\n\nCommon causes:\n• Stress from exams, work, or family pressure\n• PCOS, thyroid issues, nutrition gaps\n• Sudden weight change\n• Over-exercise or under-eating\n\nNormal cycle length is 21-35 days. If your cycle stays outside this range for 3+ months, visit a gynecologist.",
    },
    {
      keys: ["chhaupadi", "chhau", "shed", "baahira", "bahira", "छाउ", "छाउपडी"],
      topic: "Chhaupadi",
      response:
        "Chhaupadi (छाउपडी) is a harmful practice criminalized in Nepal in 2018. It is not required for health or dignity.\n\nIt can be dangerous because of cold, isolation, animal attacks, and assault.\n\nIf someone is being forced into Chhaupadi:\n📞 Nepal Police: 100\n📞 Women's helpline: 1145\n📞 WOREC: 01-4102030\n\nYou have the right to stay safely inside your home during your period.",
    },
    {
      keys: ["hygiene", "safa", "pad", "kapada", "cloth", "clean", "cup", "प्याड", "कपडा"],
      topic: "Hygiene tips",
      response:
        "Menstrual hygiene basics:\n\n✅ Safe options:\n• Sanitary pads, changed every 4-6 hours\n• Menstrual cups, reusable and eco-friendly\n• Clean cotton cloth when washed correctly\n\n⚠️ If using cloth:\n• Wash with soap and hot water\n• Dry in direct sunlight\n• Store only when fully dry\n\n❌ Never use ash, sand, leaves, or damp cloth because infection risk is serious.",
    },
    {
      keys: ["mood", "angry", "sad", "emotional", "ris", "anxiety", "cry", "रिस", "दुखी"],
      topic: "Mood swings",
      response:
        "Mood swings during periods are real. Hormone changes can affect serotonin and stress response.\n\n🌿 Mood support:\n• 15-20 minutes of sunlight\n• Banana and dark chocolate for magnesium\n• Write what you feel\n• Gentle walk or stretching\n• Talk to someone you trust\n\nYou are not weak or dramatic. Your feelings are valid.",
    },
    {
      keys: ["pcos", "hair", "acne", "weight", "पीसीओएस"],
      topic: "PCOS",
      response:
        "PCOS can cause irregular periods, acne, facial hair growth, weight changes, and difficulty with ovulation.\n\nHelpful habits:\n• Regular meals with protein and fiber\n• Walking or strength exercise most days\n• Sleep routine and stress care\n• Medical checkup for hormones, thyroid, and blood sugar\n\nIf your period has not come for 3 months, please see a gynecologist.",
    },
    {
      keys: ["first", "menarche", "school", "पहिलो", "किशोरी"],
      topic: "First period",
      response:
        "Your first period can feel confusing, but it is a normal sign of puberty.\n\nCarry a small pouch with pads or clean cloth, underwear, soap, and a paper bag. Change pads every 4-6 hours. If bleeding soaks a pad every hour, or pain is unbearable, tell a trusted adult and seek care.",
    },
    {
      keys: ["pregnant", "pregnancy", "sex", "गर्भ", "pregnancy"],
      topic: "Pregnancy concern",
      response:
        "A late period can happen from stress, PCOS, thyroid issues, nutrition changes, or pregnancy if you had unprotected sex.\n\nFor pregnancy concern, use a urine pregnancy test from the first day of a missed period. For urgent worries, visit a health post or gynecologist. Your privacy matters.",
    },
    {
      keys: ["doctor", "hospital", "clinic", "help", "gyne", "डाक्टर", "अस्पताल"],
      topic: "Find a doctor",
      response:
        "You can use the Hospital Finder page to filter by province, district, service, and hospital type.\n\nSeek urgent care if you have very heavy bleeding, fever, foul-smelling discharge, severe one-sided pain, dizziness, or pregnancy-related pain.",
    },
    {
      keys: ["food", "eat", "diet", "achar", "sour", "nutrition", "खाना", "अमिलो"],
      topic: "Food and nutrition",
      response:
        "During periods, focus on iron, magnesium, hydration, and warm meals.\n\nTry dal, spinach, eggs, sesame, banana, yogurt, turmeric milk, ginger tea, and lemon with greens for iron absorption.\n\nSour foods like achar do not damage your period. If a food upsets your stomach personally, avoid it gently.",
    },
  ],

  hospitals: [
    { id: 1, name: "Paropakar Maternity Hospital", nameNe: "परोपकार प्रसूति तथा स्त्री रोग अस्पताल", province: "Bagmati", district: "Kathmandu", address: "Thapathali, Kathmandu", phone: "01-4215072", type: "Government", services: ["Gynecology", "Obstetrics", "Family Planning"], fee: "Free / Subsidized", rating: 4.2, openHours: "24/7" },
    { id: 2, name: "Karnali Province Hospital", nameNe: "कर्णाली प्रदेश अस्पताल", province: "Karnali", district: "Surkhet", address: "Birendranagar, Surkhet", phone: "083-520516", type: "Government", services: ["Gynecology", "Obstetrics"], fee: "Free", rating: 3.8, openHours: "Sun-Fri 8AM-5PM" },
    { id: 3, name: "Lumbini Provincial Hospital", nameNe: "लुम्बिनी प्रादेशिक अस्पताल", province: "Lumbini", district: "Rupandehi", address: "Butwal-10, Rupandehi", phone: "071-540199", type: "Government", services: ["Gynecology", "Obstetrics", "Family Planning"], fee: "Free / Subsidized", rating: 4.0, openHours: "24/7" },
    { id: 4, name: "B.P. Koirala Institute of Health Sciences", nameNe: "बी.पी. कोइराला स्वास्थ्य विज्ञान प्रतिष्ठान", province: "Koshi", district: "Sunsari", address: "Dharan, Sunsari", phone: "025-525555", type: "Government", services: ["Gynecology", "Obstetrics", "Mental Health"], fee: "Subsidized", rating: 4.3, openHours: "24/7" },
    { id: 5, name: "Janakpur Provincial Hospital", nameNe: "जनकपुर प्रादेशिक अस्पताल", province: "Madhesh", district: "Dhanusha", address: "Janakpurdham", phone: "041-520133", type: "Government", services: ["Gynecology", "Obstetrics", "Family Planning"], fee: "Free / Subsidized", rating: 3.9, openHours: "24/7" },
    { id: 6, name: "Pokhara Academy of Health Sciences", nameNe: "पोखरा स्वास्थ्य विज्ञान प्रतिष्ठान", province: "Gandaki", district: "Kaski", address: "Ramghat, Pokhara", phone: "061-520067", type: "Government", services: ["Gynecology", "Obstetrics"], fee: "Subsidized", rating: 4.1, openHours: "24/7" },
    { id: 7, name: "Seti Provincial Hospital", nameNe: "सेती प्रादेशिक अस्पताल", province: "Sudurpashchim", district: "Kailali", address: "Dhangadhi, Kailali", phone: "091-524281", type: "Government", services: ["Gynecology", "Obstetrics", "Family Planning"], fee: "Free / Subsidized", rating: 3.8, openHours: "24/7" },
    { id: 8, name: "Dhulikhel Hospital", nameNe: "धुलिखेल अस्पताल", province: "Bagmati", district: "Kavrepalanchok", address: "Dhulikhel", phone: "011-490497", type: "Community", services: ["Gynecology", "Obstetrics", "Mental Health"], fee: "Subsidized", rating: 4.4, openHours: "24/7" },
    { id: 9, name: "Patan Hospital", nameNe: "पाटन अस्पताल", province: "Bagmati", district: "Lalitpur", address: "Lagankhel, Lalitpur", phone: "01-5522278", type: "Government", services: ["Gynecology", "Obstetrics", "Family Planning", "Mental Health"], fee: "Subsidized", rating: 4.2, openHours: "24/7" },
    { id: 10, name: "Rapti Provincial Hospital", nameNe: "राप्ती प्रादेशिक अस्पताल", province: "Lumbini", district: "Dang", address: "Tulsipur, Dang", phone: "082-521624", type: "Government", services: ["Gynecology", "Obstetrics"], fee: "Free / Subsidized", rating: 3.7, openHours: "Sun-Fri 8AM-5PM" },
    { id: 11, name: "Mechi Provincial Hospital", nameNe: "मेची प्रादेशिक अस्पताल", province: "Koshi", district: "Jhapa", address: "Bhadrapur, Jhapa", phone: "023-520172", type: "Government", services: ["Gynecology", "Obstetrics"], fee: "Free / Subsidized", rating: 3.8, openHours: "24/7" },
    { id: 12, name: "Narayani Hospital", nameNe: "नारायणी अस्पताल", province: "Madhesh", district: "Parsa", address: "Birgunj, Parsa", phone: "051-521993", type: "Government", services: ["Gynecology", "Obstetrics", "Family Planning"], fee: "Free / Subsidized", rating: 3.9, openHours: "24/7" },
    { id: 13, name: "Manipal Teaching Hospital", nameNe: "मणिपाल शिक्षण अस्पताल", province: "Gandaki", district: "Kaski", address: "Phulbari, Pokhara", phone: "061-526416", type: "Private", services: ["Gynecology", "Obstetrics"], fee: "Paid", rating: 4.0, openHours: "24/7" },
    { id: 14, name: "Mahakali Provincial Hospital", nameNe: "महाकाली प्रादेशिक अस्पताल", province: "Sudurpashchim", district: "Kanchanpur", address: "Mahendranagar", phone: "099-525111", type: "Government", services: ["Gynecology", "Obstetrics"], fee: "Free / Subsidized", rating: 3.6, openHours: "Sun-Fri 8AM-5PM" },
    { id: 15, name: "Dailekh District Hospital", nameNe: "दैलेख जिल्ला अस्पताल", province: "Karnali", district: "Dailekh", address: "Narayan Municipality, Dailekh", phone: "089-420188", type: "Government", services: ["Gynecology", "Family Planning"], fee: "Free", rating: 3.5, openHours: "Sun-Fri 8AM-5PM" },
    { id: 16, name: "Bheri Hospital", nameNe: "भेरी अस्पताल", province: "Lumbini", district: "Banke", address: "Nepalgunj, Banke", phone: "081-520120", type: "Government", services: ["Gynecology", "Obstetrics", "Mental Health"], fee: "Subsidized", rating: 4.0, openHours: "24/7" },
    { id: 17, name: "Koshi Hospital", nameNe: "कोशी अस्पताल", province: "Koshi", district: "Morang", address: "Biratnagar, Morang", phone: "021-530103", type: "Government", services: ["Gynecology", "Obstetrics", "Family Planning"], fee: "Free / Subsidized", rating: 4.1, openHours: "24/7" },
    { id: 18, name: "Hetauda Hospital", nameNe: "हेटौंडा अस्पताल", province: "Bagmati", district: "Makwanpur", address: "Hetauda, Makwanpur", phone: "057-520602", type: "Government", services: ["Gynecology", "Obstetrics"], fee: "Free / Subsidized", rating: 3.8, openHours: "24/7" },
  ],

  ngos: [
    { id: 1, name: "Women's Rehabilitation Centre (WOREC)", focus: ["Chhaupadi Elimination", "GBV Support", "Menstrual Health"], province: "National", contact: "01-4102030", website: "worecnepal.org", description: "Leading organization fighting menstrual discrimination and Chhaupadi in Nepal since 1991.", logo: "🏠" },
    { id: 2, name: "The Pad Project Nepal", focus: ["Pad Distribution", "Education", "Rural Outreach"], province: "Multiple", contact: "info@padprojectnepal.org", website: "padproject.org", description: "Supports sanitary pad access and menstrual education for girls in underserved schools.", logo: "🌸" },
    { id: 3, name: "Hamro Cheli Nepal", focus: ["Girl Education", "Menstrual Health", "WASH"], province: "Karnali, Sudurpashchim", contact: "contact@hamrocheli.org", website: "hamrocheli.org", description: "Works in remote districts to reduce period stigma in schools and households.", logo: "📚" },
    { id: 4, name: "Days for Girls Nepal", focus: ["Reusable Pads", "Education", "Enterprise"], province: "Multiple", contact: "nepal@daysforgirls.org", website: "daysforgirls.org", description: "Provides reusable menstrual kits and practical health education.", logo: "🧵" },
    { id: 5, name: "WaterAid Nepal", focus: ["WASH", "School Toilets", "Policy"], province: "National", contact: "01-4516025", website: "wateraid.org/np", description: "Improves water, sanitation, and hygiene access, including menstrual hygiene facilities.", logo: "💧" },
    { id: 6, name: "UNICEF Nepal", focus: ["Adolescent Health", "WASH", "Education"], province: "National", contact: "01-5523200", website: "unicef.org/nepal", description: "Supports menstrual hygiene management in schools and communities.", logo: "🤝" },
    { id: 7, name: "Miteri Recycle Center", focus: ["Eco Pads", "Waste Reduction", "Training"], province: "Bagmati", contact: "info@miteri.org", website: "miteri.org", description: "Promotes sustainable menstrual products and waste-conscious period care.", logo: "♻️" },
    { id: 8, name: "Rural Women Network Nepal", focus: ["Advocacy", "Health Rights", "Community Leaders"], province: "Gandaki, Lumbini", contact: "9800000000", website: "rwnnepal.org", description: "Trains local women leaders to challenge stigma and improve health-seeking behavior.", logo: "🌿" },
    { id: 9, name: "Safe Pad Nepal", focus: ["Pad Banks", "School Outreach", "Emergency Kits"], province: "Madhesh, Koshi", contact: "hello@safepadnepal.org", website: "safepadnepal.org", description: "Runs pad banks and emergency menstrual hygiene support in schools.", logo: "🩸" },
    { id: 10, name: "Sathi Samuha", focus: ["Mental Health", "Peer Circles", "Adolescent Girls"], province: "Bagmati, Karnali", contact: "01-4444444", website: "sathisamuha.org", description: "Facilitates peer support groups for adolescent health and mental wellbeing.", logo: "💜" },
  ],

  articles: [
    { id: 1, title: "Understanding PCOS: Nepal's Hidden Epidemic", titleNe: "PCOS बुझ्नुहोस्: नेपालको लुकेको समस्या", category: "PCOS", summary: "1 in 5 Nepali women may have PCOS. Learn symptoms, diagnosis, and management.", readTime: "5 min", tags: ["PCOS", "Hormones", "Women's Health"], imageUrl: "./img/pcos.webp", videoUrl: "https://youtu.be/I96WO-9ZmWw?si=G8ZfMsMJ5e5hLDs4" },
    { id: 2, title: "Hygiene on a Budget: Affordable Options for Rural Nepal", titleNe: "कम खर्चमा स्वच्छता: ग्रामीण नेपालका लागि विकल्प", category: "Hygiene", summary: "Menstrual cups, clean cloth practices, reusable pads, and free product access.", readTime: "4 min", tags: ["Hygiene", "Budget", "Rural Nepal"], imageUrl: "./img/period hygenic.webp", videoUrl: "https://youtu.be/cIWvgYtFE9Y?si=bVv6kVrg6je1a9v5" },
    { id: 3, title: "Why Cramps Happen and What Helps", titleNe: "पेट दुखाइ किन हुन्छ र के गर्दा कम हुन्छ", category: "Hormones", summary: "Understand prostaglandins, heat therapy, movement, and nutrition for pain relief.", readTime: "6 min", tags: ["Pain", "Hormones"], imageUrl: "./img/period cramps.webp", videoUrl: "https://youtu.be/BgzCL0q2118?si=UTxrw42oXoqo6iBc" },
    { id: 4, title: "Endometriosis: When Pain Is Not Normal", titleNe: "Endometriosis: जब दुखाइ सामान्य हुँदैन", category: "Endometriosis", summary: "Severe period pain deserves care. Know the warning signs and care pathways.", readTime: "7 min", tags: ["Pain", "Doctor"], imageUrl: "./img/Endometriosis.webp", videoUrl: "https://youtu.be/BgzCL0q2118?si=UTxrw42oXoqo6iBc" },
    { id: 5, title: "Food Myths: Achar, Dahi, and Cold Water", titleNe: "खानाका मिथ्या: अचार, दही र चिसो पानी", category: "Nutrition", summary: "Separate cultural fear from practical nutrition during menstruation.", readTime: "3 min", tags: ["Food", "Myths"], imageUrl: "./img/Food Myths.webp", videoUrl: "https://youtu.be/cIWvgYtFE9Y?si=bVv6kVrg6je1a9v5" },
    { id: 6, title: "Mental Health and PMS", titleNe: "मानसिक स्वास्थ्य र PMS", category: "Mental Health", summary: "Hormones can affect mood. Learn gentle tools for anxiety and irritability.", readTime: "5 min", tags: ["Mood", "PMS"], imageUrl: "./img/Mental Health and PMS.webp", videoUrl: "https://youtu.be/cIWvgYtFE9Y?si=bVv6kVrg6je1a9v5" },
    { id: 7, title: "First Period Guide for Girls and Guardians", titleNe: "पहिलो महिनावारी: किशोरी र अभिभावकका लागि", category: "Hygiene", summary: "A calm, practical guide for school, home, supplies, and supportive conversations.", readTime: "5 min", tags: ["First Period", "School"], imageUrl: "./img/First Period Guide for Girls and Guardians.webp", videoUrl: "https://youtu.be/I96WO-9ZmWw?si=G8ZfMsMJ5e5hLDs4" },
    { id: 8, title: "Menstrual Cups in Nepal", titleNe: "नेपालमा menstrual cup", category: "Hygiene", summary: "What cups are, who can use them, how to clean them, and common concerns.", readTime: "6 min", tags: ["Cup", "Eco"], imageUrl: "./img/Menstrual Cups in Nepal.webp", videoUrl: "https://youtu.be/cIWvgYtFE9Y?si=bVv6kVrg6je1a9v5" },
    { id: 9, title: "Chhaupadi: Law, Safety, and Support", titleNe: "छाउपडी: कानुन, सुरक्षा र सहयोग", category: "Mental Health", summary: "Understand rights, risks, and support options for families and communities.", readTime: "6 min", tags: ["Chhaupadi", "Rights"], imageUrl: "./img/Chhaupadi.webp", videoUrl: "https://youtu.be/Fz4WKkQ4G0Y?si=tNF0K28pJGIIS2f-" },
    { id: 10, title: "Cycle Tracking Without Shame", titleNe: "लाज बिना cycle tracking", category: "Hormones", summary: "Tracking helps you understand patterns, prepare supplies, and know when to seek care.", readTime: "4 min", tags: ["Tracker", "Body Literacy"], imageUrl: "./img/Cycle Tracking Without Shame.webp", videoUrl: "https://youtu.be/I96WO-9ZmWw?si=G8ZfMsMJ5e5hLDs4" },
  ],

  posts: [
    {
      id: 1,
      author: "Sunflower from Chitwan",
      category: "Question",
      time: "2 hours ago",
      body: "के PCOS भएकाहरूले नियमित व्यायाम गर्दा cycle नियमित हुन्छ? मेरो ३ महिना देखि period आएको छैन।",
      likes: 47,
      comments: 5,
      tags: ["PCOS", "Cycle"],
      commentsList: [
        { author: "Rose from Pokhara", time: "1 hour ago", text: "मलाई पनि PCOS छ र walking 30 minutes गर्दा cycle slightly better भयो। Doctor पनि भेट्नुहोस्।" },
        { author: "Marigold from Kathmandu", time: "45 min ago", text: "Yes! मैले yoga र light exercise सुरु गरेपछि 2 महिनामा period आयो। Metformin पनि doctor ले दिए।" },
        { author: "Lily from Lalitpur", time: "30 min ago", text: "Strength training र protein rich diet पनि help गर्छ। तर patience चाहिन्छ, 3-4 महिना लाग्छ।" },
        { author: "Daisy from Bharatpur", time: "15 min ago", text: "म पनि PCOS छ। Doctor भेट्दा thyroid test पनि garauna bhayo. PCOS मा thyroid pani connected hunchha." },
        { author: "Anonymous from Chitwan", time: "Just now", text: "Keep tracking. मैले app मा track गरेपछि doctor लै details दिएर भेटेपछि treatment सुरु गरे।" }
      ]
    },
    {
      id: 2,
      author: "Marigold from Humla",
      category: "Experience",
      time: "5 hours ago",
      body: "म Chhaupadi मा बस्न विवश भएकी थिएँ। WOREC ले मलाई सहयोग गर्‍यो। अहिले म घरभित्र बस्छु र स्वस्थ छु।",
      likes: 203,
      comments: 23,
      tags: ["Chhaupadi", "Support"],
      commentsList: [
        { author: "Sunflower from Bajura", time: "4 hours ago", text: "तिमीलाई सुन्दर कुरा सुनाउनु भएकोमा धन्यवाद। म पनि Humla बाट Chuhaupadi विरोधी आन्दोलनमा सँगै छु।" },
        { author: "Lotus from Dhangadhi", time: "3 hours ago", text: "साह्रै प्रेरणादायी कथा हो यो। WOREC को काम उत्कृष्ट छ। म पनि तिनीहरूसँग जोडिन चाहन्छु।" },
        { author: "Jasmine from Surkhet", time: "3 hours ago", text: "मेरो दिदीले पनि Chhaupadi बाट बच्न WOREC ले support गरेको थियो। अहिले उनी स्कूल पढ्छिन्।" },
        { author: "Orchid from Baitadi", time: "2 hours ago", text: "म अझै पनि गाउँमा सुरक्षित ठाउँ पाउन सकिन। पुलिस र महिला हेल्पलाइन 1145 लाइ सम्पर्क गर्न सकिन्छ?" },
        { author: "Daisy from Achham", time: "2 hours ago", text: "तिम्रो साहसको प्रशंसा गर्न सकिन। छाउपडीको परंपरा अब बदल्ने बेला आएको छ।" },
        { author: "Hibiscus from Doti", time: "1 hour ago", text: "म पनि सुरक्षित बस्न सफल भएकी छु। यो app ले सहयोग भयो। म पनि आफ्नो कथा शेयर गर्न चाहन्छु।" },
        { author: "Anonymous from Humla", time: "1 hour ago", text: "मेरो आमा पनि यो पNDEMIC बाट पुछ्याउन शक्ति दिएकी छिन्। धन्यबाद Didi।" },
        { author: "Rhododendron from Dadeldhura", time: "45 min ago", text: "म पनि सुरक्षित बस्न कोशिश गर्दै छु। Police लाइ report गर्ने हो भने कसरी गर्ने?" },
        { author: "Marigold from Humla", time: "40 min ago", text: "WOREC लाई 01-4102030 मा सम्पर्क गर्न सकिन्छ। उनीहरू सहयोग गर्न्छन्।" },
        { author: "Lily from Kailali", time: "30 min ago", text: "मेरो neighbor पनि छाउपडीबाट मुक्त भएकी छिन्। अहिले उनी cooperative मा काम गर्छिन्।" },
        { author: "Sunflower from Kanchanpur", time: "20 min ago", text: "म पनि छाउपडी विरोधी आन्दोलनमा सामेल भएर काम गर्दै छु। सबै Mahilakahरू लाई सुरक्षित घर चाहिएको छ।" },
        { author: "Anonymous from Surkhet", time: "15 min ago", text: "तिम्रो कथा सुनाउनु भएकोमा धन्यवाद। म पनि आफ्नो बुढाखालीको कथा शेयर गर्न तयार छु।" },
        { author: "Orchid from Jumla", time: "10 min ago", text: "Chhaupadi band garnu agadi ko ho. Mahilako samaaj maa izzat ra suraksha sabai ko adhikaar ho." },
        { author: "Daisy from Kalikot", time: "8 min ago", text: "Mero ghar maa pani yehi practice theo. Aaja chhau ghar banayeko dekhyera aaghi ko laagchhu." },
        { author: "Anonymous", time: "5 min ago", text: "साहसित włas कहरो संघर्ष ले यो संसार परिवर्तन गर्न सक्छ। हामी सबै सँगै छौं।" },
        { author: "Lotus from Bajhang", time: "4 min ago", text: "म पनि छाउपडी बाट मुक्त भएको छु। अहिले म आफ्नो छोरी लाई पनि सुरक्षित बसाउन सक्छु।" },
        { author: "Rose from Baitadi", time: "3 min ago", text: "म पनि छाउपडी विरोधमा आवाज उठाउन चाहन्छु। हामी सबै Mahilakahरू लाई सहयोग चाहिएको छ।" },
        { author: "Anonymous from Humla", time: "2 min ago", text: "WOREC ले मेरो परिवारलाई पनि सहयोग गरेको थियो। धन्यबाद उनीहरूलाई।" },
        { author: "Jasmine from Surkhet", time: "1 min ago", text: "म पनि छाउपडी बाट मुक्त भएकी छु। अहिले म आफ्नो सिस्तर लाई पनि support गर्दै छु।" },
        { author: "Hibiscus from Kanchanpur", time: "Just now", text: "सुरक्षित घर हाम्रो अधिकार हो। हामी सबै सँगै यो लडाइँ जित्ने छौं।" },
        { author: "Anonymous from Dadeldhura", time: "Just now", text: "म पनि सहयोग चाहन्छु। मेरो परिवार पनि छाउपडी बाट पिडित छ।" },
        { author: "Lily from Darchula", time: "Just now", text: "म पनि छाउपडी बाट मुक्त भएको छु। अहिले म स्कूल पढ्छु र doctor पनि भेट्छु।" },
        { author: "Optional Flower", time: "Just now", text: "सुरक्षित बस्नको लागि धन्यवाद PeriodSathi लाई। यो platform ले हामीलाई आवाज दिएको छ।" }
      ]
    },
    {
      id: 3,
      author: "Lotus from Pokhara",
      category: "Advice",
      time: "Yesterday",
      body: "पहिलो दिन अदुवा चिया र heating bag ले मलाई धेरै राहत दिन्छ। स्कूलमा extra pad बोकेर जानु helpful छ।",
      likes: 124,
      comments: 3,
      tags: ["Cramps", "School"],
      commentsList: [
        { author: "Sunflower from Chitwan", time: "Yesterday", text: "अदुवा चिया + honey मलाई पनि मद्दत गर्छ। म पनि school मा extra pad र sanitary napkin लाई जान्छु।" },
        { author: "Marigold from Pokhara", time: "Yesterday", text: "Hot water bottle पनि cramp मा धेरै राम्रो छ। Evening मा warm milk पिun pani help garxa." },
        { author: "Anonymous from Pokhara", time: "Yesterday", text: "मैले पनि यही tip follow गरेपछि दुखाइ कम भयो। धन्यवाद शेयर गर्नु भएकोमा।" }
      ]
    },
    {
      id: 4,
      author: "Jasmine from Biratnagar",
      category: "Question",
      time: "Yesterday",
      body: "Menstrual cup use गर्दा virginity मा असर पर्छ भन्ने कुरा सत्य हो?",
      likes: 88,
      comments: 4,
      tags: ["Cup", "Myth"],
      commentsList: [
        { author: "Lotus from Kathmandu", time: "Yesterday", text: "यो मिथ्या हो। Cup use गर्दा virginity मा कुनै असर पर्दैन। यो बारे डराउनु पर्दैन। Safe र eco-friendly छ।" },
        { author: "Orchid from Lalitpur", time: "Yesterday", text: "मैले cup use गर्दैछु र कुनै समस्या छैन। Doctor पनि भेटेर सोध्नुहोस्, उनीहरूले clear गरेर सुनाउँछन्।" },
        { author: "Daisy from Bhaktapur", time: "Yesterday", text: "Virginity ह的定义 धेरै misleading छ। Cup लाई उपयोग गर्नु अरू कुरा हो। अझै पनि सꭇnful बनाउने कुरा छैन।" },
        { author: "Rhododendron from Biratnagar", time: "Yesterday", text: "मैले cup use गर्न लाग्दा डराएकी थिएँ। तर अब मलाई लाग्छ यो सच्चै राम्रो option हो।" }
      ]
    },
    {
      id: 5,
      author: "Rhododendron from Surkhet",
      category: "Vent",
      time: "2 days ago",
      body: "घरमा मन्दिर र kitchen जान नदिँदा धेरै नराम्रो लाग्छ। तर अहिले facts पढेर म बोल्न सिक्दैछु।",
      likes: 176,
      comments: 2,
      tags: ["Taboo", "Family"],
      commentsList: [
        { author: "Sunflower from Surkhet", time: "2 days ago", text: "म पनि यस्तै अनुभव गरेकी छु। Facts पढेर आफ्नो family लाई समझाउन सकिन्छ। धन्यवाद शेयर गर्नु भएकोमा।" },
        { author: "Lotus from Banke", time: "2 days ago", text: "मेरो आमाले पनि यो बारे धेरै कुरा गर्छिन्। हामीले उनलाई यो app देखाउने चाहिँदै छौं। धन्यवाद।" }
      ]
    },
    {
      id: 6,
      author: "Orchid from Kathmandu",
      category: "Advice",
      time: "3 days ago",
      body: "Mood swings हुँदा journal लेख्नु र walk गर्नाले help गर्छ। आफूलाई दोष नदिनुहोस्।",
      likes: 91,
      comments: 2,
      tags: ["MoodSwings", "SelfCare"],
      commentsList: [
        { author: "Marigold from Kathmandu", time: "3 days ago", text: "Journal लेख्नु राम्रो सुझाव हो। म पनि mood swings हुँदा music सुन्छु र थोरै walk गर्छु।" },
        { author: "Jasmine from Kathmandu", time: "3 days ago", text: "आफूलाई दोज नदिनु भन्ने कुरा धेरै deep छ। हामीहरूले आफ्नो feeling लाई accept गर्नupayog garna parcha." }
      ]
    },
    {
      id: 7,
      author: "Daisy from Janakpur",
      category: "Experience",
      time: "4 days ago",
      body: "विद्यालयमा pad disposal bin राखेपछि हाम्रो attendance धेरै राम्रो भएको छ। सुविधा हुँदा shame कम हुन्छ।",
      likes: 156,
      comments: 3,
      tags: ["School", "WASH"],
      commentsList: [
        { author: "Rhododendron from Janakpur", time: "4 days ago", text: "मेरो school मा पनि disposal bin छ र attendance बैंक बढेको छ। Infrastructure सुधारले ठुलो फरक पार्छ।" },
        { author: "Lily from Dhanusha", time: "4 days ago", text: "यो सच्चै राम्रो initiative हो। म पनि आफ्नो school लाई disposal bin install गर्न प्रेरित गरेकी छु।" },
        { author: "Hibiscus from Mahottari", time: "4 days ago", text: "मेरो school मा पनि यस्तो बेस्ट प्र्याक्टिस चाहिन्छ। सुख्खक लाग्न सकिन्छ कि कसरी गर्ने?" }
      ]
    },
    {
      id: 8,
      author: "Hibiscus from Dang",
      category: "Question",
      time: "5 days ago",
      body: "तीन दिन मात्र period आउनु normal हो? Cycle चाहिँ ३० दिनको हुन्छ।",
      likes: 62,
      comments: 2,
      tags: ["Normal", "Cycle"],
      commentsList: [
        { author: "Sunflower from Dang", time: "5 days ago", text: "Normal cycle 21-35 days सम्म हुन्छ। 3 दिनको period पनि normal हो। Stress, diet, exercise ले cycle मा असर पार्छ।" },
        { author: "Lotus from Ghorahi", time: "5 days ago", text: "मेरो cycle पनि 30-32 days को हुन्छ र period 3-4 दिन मात्र हुन्छ। Doctor ले पनि normal भन्नुभयो।" }
      ]
    },
    {
      id: 9,
      author: "Lily from Dhangadhi",
      category: "Advice",
      time: "1 week ago",
      body: "कपडा प्रयोग गर्नु परे soap ले धुने, घाममा सुकाउने, र dry ठाउँमा राख्ने। लुकाएर ओसिलो नराख्नु।",
      likes: 141,
      comments: 2,
      tags: ["Hygiene", "Cloth"],
      commentsList: [
        { author: "Marigold from Kailali", time: "1 week ago", text: "यो सबभन्दा राम्रो hygiene advice हो। मैले पनि cloth प्रयोग गर्दैछु र यही नियम पालना गर्छु।" },
        { author: "Rose from Baitadi", time: "1 week ago", text: "धन्यवाद यो जानकारीको लागि। मेरो आमाले पनि cloth प्रयोग गर्छिन् र उनलाई यो सुझाव उपयोगी लाग्छ।" }
      ]
    },
    {
      id: 10,
      author: "Rose from Lalitur",
      category: "Experience",
      time: "1 week ago",
      body: "Doctor सँग कुरा गरेपछि मेरो severe pain endometriosis हुन सक्छ भनेर थाहा भयो। Pain लाई ignore नगर्नुहोस्।",
      likes: 189,
      comments: 3,
      tags: ["Endometriosis", "Doctor"],
      commentsList: [
        { author: "Sunflower from Patan", time: "1 week ago", text: "मेरो DIDI ले पनि endometriosis भयो। Surgery पनि भयो र अब राम्रो छिन्। Early checkup जरुरी छ।" },
        { author: "Jasmine from Bhaktapur", time: "1 week ago", text: "मेरो पनि severe pain थियो र endometriosis पाइयो। Ignore नगर्नु हो। Doctor लाई भेट्नुहोस्।" },
        { author: "Lotus from Kathmandu", time: "1 week ago", text: "पीडा ignore नगर्नु भन्ने कुरा धेरै महत्त्वपूर्ण छ। म पनि doctor भेट्ने तayar छु। धन्यवाद साझा गर्नु भएकोमा।" }
      ]
    },
  ],
};
